# Generated by Django 3.1.4 on 2022-01-31 07:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220131_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
