# Generated by Django 3.1.4 on 2022-01-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220131_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='grade',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike'), ('without', 'without')], default='without', max_length=7, verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.commentary', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='api.video', verbose_name='video_commentary'),
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
    ]
