# Generated by Django 3.1.4 on 2022-01-31 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20220131_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='author_like'),
        ),
        migrations.AlterField(
            model_name='like',
            name='grade',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('without', 'without')], default='without', max_length=7, verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.video', verbose_name='video_like'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.video', verbose_name='video_subscription'),
        ),
    ]
